version: '3'

services:
    db:
        image:  postgres:12-alpine
        env_file: 
            - .env
    edu_service:
        build: .
        command: sh -c "./bin/wait_for.sh db:5432 -- ./bin/startup.sh"
        env_file: 
            - .env
        volumes:
            - .:/src
        ports:
            - "8000:8000"
        depends_on: 
            - db
