# Generated by Django 3.0.8 on 2020-07-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school_id',
            new_name='school',
        ),
    ]
